
- hosts: all
  become_method: sudo
  become: yes
  remote_user: ec2-user 

  vars:
    oscap_profile: xccdf_org.ssgproject.content_profile_standard
    oscap_policy: ssg-rhel7-ds

  tasks:

  - name: install openscap scanner
    package:
      name: "{{ item }}"
      state: latest
    with_items:
    - openscap-scanner
    - scap-security-guide

  - block:
    - name: run openscap
      command: oscap xccdf eval \
        --profile {{ oscap_profile }} \
        --results-arf /tmp/oscap-arf.xml \
        --report /tmp/oscap-report.html \
        --fetch-remote-resources \
        /usr/share/xml/scap/ssg/content/{{ oscap_policy }}.xml
      register: command_result
      failed_when: "'OpenSCAP Error' in command_result.stderr"

    always:
    - name: download report
      fetch:
        src: /tmp/oscap-report.html
        dest: ./oscap-reports/{{ inventory_hostname }}.html
        flat: yes